[project]
name = "penney-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bitarray>=3.7.1",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
]
